### PR TITLE
Minor fixes and updates for DST scripts

### PR DESCRIPTION
**Pull request by Mehrad0711**
- Fixing a couple of bugs for dst module
- Switching from pytorch_pretrained_bert  to transformers model to allow better development

### CODE REVIEW

**Comment by zqwerty** [comment]
Thanks! We'll fix the bugs. However, 
> Switching from pytorch_pretrained_bert to transformers model to allow better development 

needs more changes, see https://github.com/huggingface/transformers#migrating-from-pytorch-pretrained-bert-to-transformers. I'm sorry we may not use your changes directly.

**Comment by Mehrad0711** [comment]
Hi, I see that the bug fixes are adopted in a new PR (#37). 
I can update my commits to account for changes you mentioned for migrating to transformers. 
Shall I do it or is it a future issue?

**Comment by Mehrad0711** [comment]
Also, I think standalone scripts containing Chinese characters need utf-8 encoding as a header to run with python3.

**Comment by zqwerty** [comment]
> Hi, I see that the bug fixes are adopted in a new PR (#37).
> I can update my commits to account for changes you mentioned for migrating to transformers.
> Shall I do it or is it a future issue?

We would greatly appreciate it if you do so. ^_^ We would thank you in https://github.com/thu-coai/Convlab-2#team.

> Also, I think standalone scripts containing Chinese characters need utf-8 encoding as a header to run with python3.

I see. we will add it.

**Comment by Mehrad0711** [comment]
Hi,
I pushed the code and also tested locally to make sure it runs correctly. However please check for yourself before merging. Ther "comet" models can also use transformers, but I saw they weren't being used for DST tasks. 

Additionally, I added subsampling option for faster debugging. I can remove it if you think that is unnecessary; or can add it to other modules as well for consistency.

**Comment by zqwerty** [comment]
Thank you! @function2-llx please check the changes. I think subsampling may not be necessary.

**Review by zqwerty — CHANGES_REQUESTED** [review]
Cool~ I've viewed your changes. I think the change from `pytorch_pretrained_bert` to `transformers` is successful. Thanks! Please remove changes for subsampling.

**Review by zqwerty — APPROVED** [review]

**Comment by zqwerty** [comment]
Thanks for your contribution!

**Pull request merged**
