### PR TITLE
DQN

### PR DESCRIPTION
**Pull request by brunonishimoto**
**Description:**

Basic version of DQN algorithm using a epsilon greedy policy at folder **`convlab2/policy/dqn`**

- [X] class `MemoryReplay` (which has a limited size) (file **`convlab2/policy/rlmodule.py`**)
- [X] class `EpsilonGreedyPolicy` (file **`convlab2/policy/rlmodule.py`**)
- [X] script to extract the statistics of all composite actions in dataset (file **`data/multiwoz/extract_all_act.py`**)
- [X] file with the statistics of all composite actions in dataset (file **`data/multiwoz/da_slot_cnt.json`**)

Please, any feedback for improving the code or fixing any bug are welcome.

**Reference Issues:** #96 ([Feature] Improve networks and memory implementations)

### CODE REVIEW

**Comment by zqwerty** [comment]
@truthless11 @liangrz15 please have a look

**Review by truthless11 — APPROVED** [review]

**Comment by zqwerty** [comment]
Thanks! Do you have any results for the improvement?

**Comment by brunonishimoto** [comment]
Actually I do not have any results for the improvement.
I am with the same problem than in PPO settings (I get very high losses and a low success rate).

I would appreciate if there are any advise for these problems

**Comment by zqwerty** [comment]
Thanks! we will re-test the policy module with newly updated simulator

**Comment by hrwise-nlp** [comment]
Hey, I just re-test the DQN policy with a newly updated simulator. 
I notice the success rate is pretty low.
Could u please your results?

image

**Pull request merged**
